import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import type { Metadata } from 'next';
import { Murecho } from 'next/font/google';
import './globals.css';

const murecho = Murecho({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={murecho.className}>
        <div className='flex flex-col rounded-2xl bg-slate-100 min-h-screen'>
          <Header />
          <main className='flex self-center grow custom_max_content_width'>
            <section className='grow flex gap-6'>
              <Sidebar />
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
